#!/bin/bash

apt install -y pipewire-audio
apt install -y pipewire-audio-client-libraries
apt install -y pipewire-libcamera
apt install -y pipewire-v4l2
apt install -y gstreamer1.0-pipewire
apt install -y alsa-firmware-loaders
apt install -y alsa-tools
apt install -y alsa-utils
apt install -y alsa-topology-conf
apt install -y alsa-ucm-conf
apt install -y libasound2-plugins
apt install -y ubuntu-restricted-extras
apt install -y libavcodec-extra
apt install -y gstreamer1.0-plugins-*
apt install -y ffmpeg
apt install -y mesa-vulkan-drivers
apt install -y mesa-va-drivers
apt install -y libgl1-mesa-dri
apt install -y libglx-mesa0
apt install -y mesa-utils
apt install -y libvulkan1
apt install -y vulkan-tools
apt install -y curl
apt install -y qbittorrent
apt install -y strawberry
apt install -y gnome-sound-recorder
apt install -y smplayer
apt install -y fuse
apt install -y libfuse2
apt install -y unzip
apt install -y p7zip-full
apt install -y rar
apt install -y unrar
apt install -y tar
apt install -y gzip
apt install -y bzip2
apt install -y xz-utils
apt install -y file-roller
apt install -y synaptic
apt install -y gimp
apt install -y gimp-help-hu
apt install -y shotwell
apt install -y gnome-screenshot
apt install -y gnome-calculator
apt install -y gnome-calendar
apt install -y gnome-disk-utility
apt install -y gnome-system-monitor
apt install -y gnome-shell-extensions
apt install -y gnome-tweaks
apt install -y gedit
apt install -y gedit-plugins
apt install -y evince
apt install -y vainfo
apt install -y moreutils
apt install -y net-tools
apt install -y wimtools
apt install -y lm-sensors
apt install -y psensor
apt install -y thermald
apt install -y power-profiles-daemon
apt install -y stress
apt install -y inxi
apt install -y dmidecode
apt install -y smartmontools
apt install -y htop
apt install -y cups
apt install -y system-config-printer
apt install -y printer-driver-all
apt install -y printer-driver-cups-pdf
apt install -y xsane
apt install -y libsane1
apt install -y sane-utils
apt install -y simple-scan
apt install -y avahi-daemon
apt install -y avahi-utils
apt install -y libnss-mdns
apt install -y avahi-autoipd
apt install -y bluez
apt install -y bluez-tools
apt install -y bluez-firmware
apt install -y bluez-cups
apt install -y bluez-obexd
apt install -y libspa-0.2-bluetooth
sed -i 's/#AutoEnable=true/AutoEnable=true/' /etc/bluetooth/main.conf
apt install -y ufw
apt install -y gufw
apt install -y fonts-dejavu
apt install -y fonts-liberation
apt install -y fonts-noto-core
apt install -y bibata-cursor-theme

apt autoremove --purge -y
apt autoclean
apt clean

echo 'A TELEPÍTÉS BEFEJEZŐDÖTT, KÉREM, HOGY INDÍTSA ÚJRA A SZÁMÍTÓGÉPÉT!'
